# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20181016_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipients',
            new_name='recipient',
        ),
    ]
