# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_auto_20181016_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='dashboard_app.User'),
            preserve_default=False,
        ),
    ]
