# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
