# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='dope', max_length=300),
            preserve_default=False,
        ),
    ]
