# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
    ]
