# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_book_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=255),
        ),
    ]
